version: '3.8'
services:
  file_upload:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./page:/var/www/html
      - ./resources/script.sh:/tmp/script.sh
    environment:
      DEBIAN_FRONTEND: noninteractive
